### ISSUE TITLE
Can't type in to the 'limit characters' field on a text element, with dynamic data in a global block

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#1021]
- Breakdance version

1.7.RC1

 - Browser & OS

Windows 11, Edge

Reproduce:

- create a global block
- add a text element
- set it dynamically to the 'post excerpt'
- go to advanced
- try to enter a number in the 'limit characters'

you can not type into the field, but you can paste a value in:

https://recordings.webxdesign.studio/recordings/AZnWLOdfYR879hH3HRCe

**Comment by eggplantstudios** [comment]
Confirming this happens for me also.

Breakdance 1.7.2
Chrome / Mac OS

Seems to happen on Global Blocks, Text Elements, with dynamic data, when trying to limit characters.

**Comment by Olegzone** [comment]
Yes, same here. 
Breakdance 1.7.2, Chrome / Mac OS.

**Comment by breakdancemoderator** [comment]
This should be addressed in Breakdance 2.0 Beta 1, but if not, please respond here and we'll re-open.

**Comment by digitalsmithy** [comment]
Still happening on BD v2, Chrome, Mac OSX. Exact steps as OP.

**Comment by clayray** [comment]
Still happening with V2.2 as of Jan 2025, using Chrome / Windows 10.
