### ISSUE TITLE
V2 Beta Icon Background Dropoff

### ISSUE THREAD

**Issue by mgexiled** [soflyy/breakdance-bugs#1068]
The update to Version 2 beta produced a glitch in my icons. It seems the icons background gets dropped off once it passes desktop breakpoint to lower res devices.

1. Create a page
2. Breakdance Pagebuilder Mode > add Icon
3. Icon Style > Solid
4. Add Background Color (e.g #E1BA66)
5. Background Color settings retain on Desktop 
6. Background Color settings are not no longer retained on Breakpoints below Desktop. 

 - Breakdance version: 2.0 Beta
 
 - Browser & OS Chrome Win 11

https://github.com/soflyy/breakdance-bugs/assets/41072075/50c64596-cad0-47a5-8323-86d370509fb4

**Comment by mikeingz** [comment]
I confirm I have the same issue and here's the culprit :
This code shouldn't be there. It not only messes up the background, but also the padding and the border radius.

![image](https://github.com/soflyy/breakdance-bugs/assets/2438157/6ceedb3b-52fa-468e-974a-67dd5b50e86d)

**Comment by braeu71** [comment]
I confirm I have the same issue.
And yes, it not only messes up the background, but also the padding and the border radius.

**Comment by gyurmey2** [comment]
I also confirm.

**Comment by danjs74** [comment]
I also confirm.

**Comment by gyurmey2** [comment]
> I also confirm.

This has already been fixed in the latest Beta version (2.0.0-beta.2)

**Comment by danjs74** [comment]
> > I also confirm.
> 
> This has already been fixed in the latest Beta version (2.0.0-beta.2)

I've just updated to 2.0.0-beta.2 and the issue is still there...

**Comment by danjs74** [comment]
> > > I also confirm.
> > 
> > 
> > This has already been fixed in the latest Beta version (2.0.0-beta.2)
> 
> I've just updated to 2.0.0-beta.2 and the issue is still there...

Actually - it has been fixed - just requires a page with the affected icons to be saved as far as i can tell...

**Comment by breakdancemoderator** [comment]
Thank you for the report and feedback; this has been fixed in Breakdance 2.0 Beta 2.
