### ISSUE TITLE
Critical: Missing Default width and height Attributes for Image Component in Breakdance 2.1+ (Causes Content Reflow on All Websites)

### ISSUE THREAD

**Issue by fatheaddrummer** [soflyy/breakdance-bugs#1170]
### Bug Description:
When using the new Image component in Breakdance 2.1 and later, the width and height attributes of the `<img>` tag are not set automatically. This results in content reflow issues because the browser cannot calculate the image dimensions without these attributes.

### Steps to Reproduce:

1. Create a new page.
2. Add the Image component to the page.
3. Select an image from the WordPress media library.
4. Save the page without making any additional changes to the Image component.
5. Preview the page in the browser and inspect the HTML of the `<img>` tag.

### Expected Behavior:
The `<img>` tag should automatically include the width and height attributes based on the dimensions of the selected image.

### Actual Behavior:
The `<img>` tag does not include width and height attributes, resulting in layout issues due to content reflow.

### Additional Notes:
Before Breakdance 2.1, the width and height attributes were set automatically. This issue likely occurred due to the introduction of manual settings for these attributes in version 2.1. However, a fallback to the default dimensions of the image source is missing.

This is a critical issue as it affects the performance and layout stability of all websites built with Breakdance 2.1 and above.

Thank you for reviewing this report!

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app) Regards

**Comment by fatheaddrummer** [comment]
Hi Breakdance team,

I want to respectfully raise this issue again, as it's been over 5 months since the original bug report, and unfortunately, the problem still persists in the latest version.

## 🐛 Summary  
Since Breakdance 2.1, the new Image component no longer sets the `width` and `height` attributes automatically on the `<img>` tag. This results in two critical issues:

1. **Content reflow during image loading**, affecting layout stability.  
2. **Broken aspect ratio**, if a user sets fixed dimensions and later replaces the image without updating the width/height manually.

Both issues severely impact the visual consistency and performance of websites built with Breakdance.

## ❗ Why this matters  
This is not a minor cosmetic bug — it breaks fundamental best practices for web performance and accessibility. Relying on manual width/height input for every image is impractical, especially for clients or less technical users.

## ✅ Suggested fix  
Here is a minimal and backward-compatible fix that adds a fallback to the image’s native dimensions (from the media library) when `set_html_width_height` is not explicitly enabled:

**For the `height` attribute:**
```twig
{% if (content.image.set_html_width_height) %}
  {{ content.image.height }}
{% elseif (content.image.from == "media_library") %}
  {{ content.image.media.sizes.full.height }}
{% endif %}
```

**For the `width` attribute:**
```twig
{% if (content.image.set_html_width_height) %}
  {{ content.image.width }}
{% elseif (content.image.from == "media_library") %}
  {{ content.image.media.sizes.full.width }}
{% endif %}
```

This ensures that the image always has valid `width` and `height` attributes, improving CLS (Cumulative Layout Shift) and preventing layout issues.

## 🙏 Final note  
I fully understand that features and bugs must be prioritized, but this is a core issue affecting all Breakdance sites that use images. I believe it deserves urgent attention and would likely require no more than 15–30 minutes to implement.

Thanks for your hard work and for considering this fix.

Best regards,  
Christian

**Comment by breakdancemoderator** [comment]
This has been addressed in Breakdance 2.5 Beta 1, which is available for [beta testing](https://breakdance.com/documentation/advanced/enable-beta-updates/).

**Comment by fatheaddrummer** [comment]
Thank you so much for the fix. I just installed Version 2.5 (stable) but I can still reproduce the issue and I don't see it fixed. I have checked it 3 times, because I could not believe it, but as far as I can evaluate, it is still the same issue. Could you please correct me or check it once again?

**Comment by TTvede** [comment]
Still reproduces on **Breakdance 3.0.0-beta.8** (WordPress 7.1, PHP 8.4.25) — confirming @fatheaddrummer's report above that 2.5 stable did not fix it.

This issue is closed as completed, so it may no longer be on anyone's list. Measurements from a current 3.0 build, in case they help.

Note on scope: the V1 `Image` element no longer exists in Breakdance 3.0, so this is measured on `Fundamental Image`, which is its successor. Four of them on one page, all pointed at media-library attachments through ACF dynamic data:

| element | `srcset` | `sizes` | `width` | `height` |
|---|---|---|---|---|
| A | ✔ 4 sources | ✔ | ✔ 1180 | ✔ 611 |
| B | ✔ 4 sources | ✔ | — | — |
| C | ✔ 4 sources | ✔ | — | — |
| D | ✔ 6 sources | ✔ | — | — |

Element A only carries dimensions because `width`/`height` were entered by hand under Advanced → Attributes. B, C and D are configured identically apart from that, and emit no dimensions at all.

So on 3.0.0-beta.8 `srcset`/`sizes` are emitted correctly for media-library images, but `width`/`height` are still missing — which is exactly the fallback the original report asked for. The practical effect is unchanged: every image without hand-entered dimensions ships with no intrinsic size, so CLS has to be handled structurally (aspect-ratio or fixed containers) on every site, and replacing an image silently breaks any dimensions that were entered manually.

The Twig fallback proposed in the April 2025 comment still looks like it would cover this.

**Comment by mnprtickets** [comment]
Still reproduces on 3.0.0-beta.9 (WordPress 7.1, PHP 8.5.10, Breakdance Zero Theme).

Tested a Fundamental Image element, inserted via the MCP edit-post tool, sourced from the media library ({"from": "media_library", "lazy_load": true, "media": {"id": <attachment id>}}, no manual dimensions entered). srcset/sizes are now populated correctly (that part was fixed alongside #1352), but the rendered <img> tag still has no width or height attributes:

<img class="bde-f-image-XXXX-100 bde-f-image" src="...jpg" loading="lazy" srcset="...1200w, ...300w, ...1024w, ...768w" sizes="(max-width: 1200px) 100vw, 1200px">

Also checked a pre-existing, non-MCP image already live in one of this site's templates (a plain Image element in the footer, not touched by MCP at all) - same result, no width/height either. So this isn't just an MCP-path issue; it looks like no Image element on beta.9 emits static width/height unless entered by hand, matching what @TTvede documented on beta.8. Re-flagging since this is closed as completed but clearly isn't, going on 3.0 now.
