### ISSUE TITLE
2.5 beta 1: Can't add attributes to icon list items

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#1257]
When using the icon list element, you can not add attributes to the items. The 'add attribute' button is there, but does nothing when clicked.

- Add a new icon list element
- Add a list item
- Go to the 'cog' settings
- Click 'Advanced'
- Click 'Add Attribute' and nothing happens

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.

**Comment by lockedm** [comment]
@breakdancemoderator did you follow the steps above? This is easily reproducable on all my 2.5.0.1 beta sites. Here's a video showing the steps and the problem:

https://recordings.webxdesign.studio/recordings/oscPUA7LCCydqKvVrMeU

**Comment by lockedm** [comment]
@breakdancemoderator  Confirming this is still an issue in BD2.5 beta 2
