### ISSUE TITLE
reCAPTCHA doesn't work if you enter your key in the "custom" tab

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#242]
reCAPTCHA only works if you enter your keys in the WP admin. Entering it directly in the Breakdance UI after choosing "custom" doesn't work

<img width="739" alt="Screen Shot 2022-08-17 at 8 58 33 PM" src="https://user-images.githubusercontent.com/53244307/185418060-3f39c6a2-a743-4a17-a344-f2552686b2bd.png">
<img width="282" alt="Screen Shot 2022-08-17 at 8 53 32 PM" src="https://user-images.githubusercontent.com/53244307/185418068-68d7ff00-7b34-47ca-a961-e3d8b7d2e151.png">
r

**Comment by louisreingold** [comment]
Related https://www.facebook.com/groups/breakdanceofficial/posts/5326110837424168/

**Comment by louisreingold** [comment]
Solved in a recent beta. Thanks for the bug report.

**Comment by mikehenze** [comment]
I still cannot get this working in rc1. Also not when using the keys in the global settings. Domain is whitelisted and works fine without BD

**Comment by mikehenze** [comment]
Its fixed in rc2 now
