### ISSUE TITLE
RC 1 - Column - Min-height set on wrapper is overridden by .breakdance .bde-column:empty rule

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#359]
Steps to reproduce:

1. Add a Columns element
2. Select one of the Columns
3. Give the Column a background image or color
4. Go to Advanced > Wrapper > Size and set its min-height to some arbitrary value larger than 80px
5. Check on the front-end and see that the min-height CSS is overridden by an 80px min-height from a .breakdance .bde-column:empty rule

This only effects empty columns, so it's only an issue if you're using columns to display background images and no other content.

**Comment by MichalisDBA** [comment]
I agree. Same thing happens to me. Empty section does not respect min height or height in general. There is always a 80px min height applied.

![307684461_10225309400596079_8008297499456167965_n](https://user-images.githubusercontent.com/68512501/191092003-ffe4d025-6b8b-4ddc-9a15-bd2bee033111.jpg)
![307159320_10225309405276196_1317662873445395760_n](https://user-images.githubusercontent.com/68512501/191091999-b2e2212a-0671-4d00-9875-76b67cc304f3.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.

**Comment by MichalisDBA** [comment]
@a-dubiel The problem still persists in latest 1.1 version for the section as i mentioned above.
