### ISSUE TITLE
Checkout page styles not working

### ISSUE THREAD

**Issue by silverlunace** [soflyy/breakdance-bugs#52]
The checkout page looks perfect in the Builder but doesn't reflect on the frontend. No matter what I do, it stays one column and won't apply any styles. Using Chrome on iMac and hosting on SiteGround.

Short video - https://share.vidyard.com/watch/BPuCwWP7Nj6uu77y8dCQ4W?

Let me know if you need any other details.

**Comment by louisreingold** [comment]
In beta 5/6 there will be some significant changes to the checkout page styling. I will check back in with you then to see it those changes solved this problem.

**Comment by silverlunace** [comment]
Awesome! Thanks Louis!

**Comment by louisreingold** [comment]
I believe this is solved in beta 5. If not, please open a new issue.

**Comment by silverlunace** [comment]
Nope, not fixed. I tried trashing the original checkout page and starting over and even that didn't help. Still one column on the frontend even though it's showing as 2 column in Breakdance editor. So, will open a new issue shortly.
