### ISSUE TITLE
Issues with sidecart scrolling.

### ISSUE THREAD

**Issue by justinfaulkner89** [soflyy/breakdance-bugs#588]
I am having issues with sidecart scrolling. This happens on my personal site and a clients site. 

Basically, when a user adds more than a few products into the scrolling the side art, the page scrolls instead of the sidecart. Meaning the user cannot scroll to and click the view basket button if they have a few items in the cart.

Here is a screenshot showing the issue:
Note how I have scrolled 1/3 down the page, but the sidecart is still showing the top of the sidecart, and hasn't scrolled.

This happens on all of my breakdance sites at the moment, so I assume it is a bug everyone is experiencing.

![316535753_10166891635535243_7000563604787628717_n](https://user-images.githubusercontent.com/119472016/204704523-5de2ce38-6aef-42f5-94ee-ede4aef6a0da.jpg)

**Comment by a-dubiel** [comment]
Hey @justinfaulkner89 what version of Breakdance are you using. Looks like we addressed this in 1.1.

**Comment by justinfaulkner89** [comment]
Hey, I just updated a site to the latest version, and still having the same issue, but now with space at the top of the cart:

![IMG_5493](https://user-images.githubusercontent.com/119472016/204943048-98dca466-48c3-4fc3-ace6-218c116cc266.PNG)

**Comment by a-dubiel** [comment]
Hey @justinfaulkner89 please try clearing your cache and regenerating CSS.

**Comment by justinfaulkner89** [comment]
Hey, I have tried clearing cache and regenerating CSS. No luck :)

**Comment by justinfaulkner89** [comment]
Hey, sure. This happens on all of my sites, here is my personal one for reference:
https://www.theshapingbay.com/shop/

I have also noticed this happening in mobile menu's too on some of my other sites. There must be others experiencing this same bug?

**Comment by a-dubiel** [comment]
<img width="173" alt="Screenshot 2022-12-05 at 16 14 24" src="https://user-images.githubusercontent.com/669243/205672761-ff0f1678-f202-4592-8b0c-79331f45e292.png">

Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
