### ISSUE TITLE
Loss of ACF fields on custom CPT taxonomy archives

### ISSUE THREAD

**Issue by lalucioledigitale** [soflyy/breakdance-bugs#819]
Version of Breakdance: v1.3
Browsers: Chrome, Safari, Firefox
Operating system: MacOS

Since I switched from version 1.2.1 to version 1.3, the ACF fields no longer work in the taxonomy archives for my custom post types. If I call the field directly in a code block, it works. But if I call it up in dynamic data, it doesn't work. This bug is very annoying because it affects many pages on my various sites.

Here's an example on this page: https://tadelaktdesigns.com/alphabet/a/

The image, part of the h1, the introduction to the list of definitions and the text for each definition are missing. All this information is in ACF fields.

Thank you in advance for your feedback.

**Comment by a-dubiel** [comment]
Thanks for your report.

> The image, part of the h1, the introduction to the list of definitions and the text for each definition are missing. All this information is in ACF fields.

Where are those fields are attached?

**Comment by lalucioledigitale** [comment]
Thanks a lot.
I hope it can be corrected soon :)

**Comment by lalucioledigitale** [comment]
I'm coming back to you because even though version 1.3.1 has been corrected and most of the ACF fields now work (many thanks for that), not everything still works correctly on the taxonomy archives.
In particular, I've noticed the following:
- I can't bring up the description (Wordpress by default) of a term in "dynamic data".
- I've created an image field with ACF for each term in each of my taxonomies, and I can't display this image in the taxonomy archive either.
Can you see if you are experiencing the same problems?

**Comment by lalucioledigitale** [comment]
Hi,
This bug has returned in version 1.4 RC1.
Thanks,
Julien.

**Comment by lalucioledigitale** [comment]
Hi,
I'm sorry, I can't give you that...

**Comment by lalucioledigitale** [comment]
For example, in my header, I use dynamic data to call up a logo which is an ACF image field. The image is displayed on all pages except the taxonomy archives.
I also call up the content of an ACF text field in dynamic data on a "text" component, but this doesn't work on the taxonomy archives.

**Comment by a-dubiel** [comment]
We just released 1.4. Consider updating it to see if this resolves your current issues.

**Comment by lalucioledigitale** [comment]
Hi, 
I've just tested with 1.4 and 1.4.1 RC1, and there's still the same problem.

**Comment by a-dubiel** [comment]
Hey, I was able to reproduce this. I passed this to our internal team. Thanks for your help. Once we have a fix in place I will update you in this thread directly.

**Comment by lalucioledigitale** [comment]
Hi,
Thanks a lot for all your work.

**Comment by a-dubiel** [comment]
@lalucioledigitale can you e-mail us at support@breakdance.com with your login credentials. We have trouble reproducing this bug reliably.

**Comment by lalucioledigitale** [comment]
Hi,
I'm sorry, I can't give you the identifiers but I think I understood what is creating the bug. It is when the ACF fields are attached to an ACF option page that it does not work.

**Comment by a-dubiel** [comment]
Alright, that helps. To make sure, when you query Options Page ACF on Archive Template, it does not work. Correct?

**Comment by a-dubiel** [comment]
Alright. I was able to reproduce it. We will fix this soon.

**Comment by louisreingold** [comment]
Without checking on your server I can't be 100% sure, but we changed dynamic data handling in 1.5 Beta 1 to solve this.

**Comment by BrockwayProd** [comment]
@louisreingold i have the same issue, and it is working for me on version 1.4.1, but on version newer than that the bug is coming back.
i am happy to share any server/site credentials with support if that help fix the issue. As it look pretty critical to me that Breakdance work with ACF.

**Comment by louisreingold** [comment]
We fixed problems with ACF term field behavior in https://breakdance.com/breakdance-1-6-rc-1/. @lalucioledigitale I believe this will fix the issues you described in your Jun 17th comment.

**Comment by BrockwayProd** [comment]
Worked like a charm :)
